-- AlterTable
ALTER TABLE `submissions` MODIFY `status` ENUM(
  'PENDING',
  'QUEUED',
  'JUDGING',
  'COMPILING',
  'RUNNING',
  'REJUDGE_QUEUED',
  'REJUDGING',
  'ACCEPTED',
  'WRONG_ANSWER',
  'TIME_LIMIT_EXCEEDED',
  'MEMORY_LIMIT_EXCEEDED',
  'RUNTIME_ERROR',
  'COMPILE_ERROR',
  'SECURITY_ERROR',
  'SYSTEM_ERROR'
) NOT NULL DEFAULT 'PENDING';

ALTER TABLE `submissions`
  ADD COLUMN `rejudge_count` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `last_rejudged_at` DATETIME(3) NULL;
