apiVersion: v1
kind: Secret
metadata:
  name: {{ include "epoch-judge.fullname" . }}-secret
  labels:
    {{- include "epoch-judge.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.mysql.password | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
  JWT_SECRET: {{ .Values.auth.jwtSecret | quote }}
  {{- if eq .Values.storage.type "s3" }}
  S3_ACCESS_KEY: {{ .Values.storage.s3.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.storage.s3.secretKey | quote }}
  {{- end }}
